### ISSUE TITLE
gdown error

### ISSUE THREAD

**Issue by sunshinejuanjuan123** [kywind/self-corr-pose#3]
gdown --id 1MOeWKoHoBK9GH6jJ-BZPvD9rj9xQdWux
/home/yuanweizhong/anaconda3/envs/PoseReloc/lib/python3.9/site-packages/gdown/cli.py:126: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Access denied with the following error:

        Cannot retrieve the public link of the file. You may need to change
        the permission to 'Anyone with the link', or have had many accesses.

You may still be able to access the file from the browser:

         https://drive.google.com/uc?id=1MOeWKoHoBK9GH6jJ-BZPvD9rj9xQdWux

**Comment by kywind** [comment]
Hi, this error might be caused by downloading a folder with gdown. You can try downloading the checkpoint files in the folder one at a time. In your case it will be `gdown 1qHipsSV-t-HyVCtPdREggENaho4wNyc6` and `gdown 1jWTd8Uftv9y5RdzqlqQ18MhRkFFbquyc`.
