### ISSUE TITLE
backward pass 

### ISSUE THREAD

**Issue by taeyeopl** [kywind/self-corr-pose#5]
Thanks for sharing the code. 
I have an issue related to backpropagation during training. Do you have any advice related to this?

> using distributed training...
world size: 1, local rank: 0
total number of videos: 190
total number of valid frames: 51854
per gpu batch size: 32
number of gpus: 1
number of iterations per gpu 20000
found vert_params: mesh.mean_v, shape: [995, 3], requires_grad: True
*found unknown params: mesh.faces, shape: [1986, 3], requires_grad: False
*found unknown params: mesh.symm_rots, shape: [2, 3, 3], requires_grad: False
found backbone_params: encoder.backbone.resnet.conv1.weight, shape: [64, 3, 7, 7], requires_grad: True
found backbone_params: encoder.backbone.resnet.bn1.weight, shape: [64], requires_grad: False
found backbone_params: encoder.backbone.resnet.bn1.bias, shape: [64], requires_grad: False
found backbone_params: encoder.backbone.resnet.layer1.0.conv1.weight, shape: [64, 64, 3, 3], requires_grad: True
found backbone_params: encoder.backbone.resnet.layer1.0.bn1.weight, shape: [64], requires_grad: False
found backbone_params: encoder.backbone.resnet.layer1.0.bn1.bias, shape: [64], requires_grad: False
found backbone_params: encoder.backbone.resnet.layer1.0.conv2.weight, shape: [64, 64, 3, 3], requires_grad: True
found backbone_params: encoder.backbone.resnet.layer1.0.bn2.weight, shape: [64], requires_grad: False
found backbone_params: encoder.backbone.resnet.layer1.0.bn2.bias, shape: [64], requires_grad: False
found backbone_params: encoder.backbone.resnet.layer1.1.conv1.weight, shape: [64, 64, 3, 3], requires_grad: True
found backbone_params: encoder.backbone.resnet.layer1.1.bn1.weight, shape: [64], requires_grad: False
found backbone_params: encoder.backbone.resnet.layer1.1.bn1.bias, shape: [64], requires_grad: False
found backbone_params: encoder.backbone.resnet.layer1.1.conv2.weight, shape: [64, 64, 3, 3], requires_grad: True
found backbone_params: encoder.backbone.resnet.layer1.1.bn2.weight, shape: [64], requires_grad: False
found backbone_params: encoder.backbone.resnet.layer1.1.bn2.bias, shape: [64], requires_grad: False
found backbone_params: encoder.backbone.resnet.layer2.0.conv1.weight, shape: [128, 64, 3, 3], requires_grad: True
found backbone_params: encoder.backbone.resnet.layer2.0.bn1.weight, shape: [128], requires_grad: False
found backbone_params: encoder.backbone.resnet.layer2.0.bn1.bias, shape: [128], requires_grad: False
found backbone_params: encoder.backbone.resnet.layer2.0.conv2.weight, shape: [128, 128, 3, 3], requires_grad: True
found backbone_params: encoder.backbone.resnet.layer2.0.bn2.weight, shape: [128], requires_grad: False
found backbone_params: encoder.backbone.resnet.layer2.0.bn2.bias, shape: [128], requires_grad: False
found backbone_params: encoder.backbone.resnet.layer2.0.downsample.0.weight, shape: [128, 64, 1, 1], requires_grad: True
found backbone_params: encoder.backbone.resnet.layer2.0.downsample.1.weight, shape: [128], requires_grad: False
found backbone_params: encoder.backbone.resnet.layer2.0.downsample.1.bias, shape: [128], requires_grad: False
found backbone_params: encoder.backbone.resnet.layer2.1.conv1.weight, shape: [128, 128, 3, 3], requires_grad: True
found backbone_params: encoder.backbone.resnet.layer2.1.bn1.weight, shape: [128], requires_grad: False
found backbone_params: encoder.backbone.resnet.layer2.1.bn1.bias, shape: [128], requires_grad: False
found backbone_params: encoder.backbone.resnet.layer2.1.conv2.weight, shape: [128, 128, 3, 3], requires_grad: True
found backbone_params: encoder.backbone.resnet.layer2.1.bn2.weight, shape: [128], requires_grad: False
found backbone_params: encoder.backbone.resnet.layer2.1.bn2.bias, shape: [128], requires_grad: False
found backbone_params: encoder.backbone.resnet.layer3.0.conv1.weight, shape: [256, 128, 3, 3], requires_grad: True
found backbone_params: encoder.backbone.resnet.layer3.0.bn1.weight, shape: [256], requires_grad: False
found backbone_params: encoder.backbone.resnet.layer3.0.bn1.bias, shape: [256], requires_grad: False
found backbone_params: encoder.backbone.resnet.layer3.0.conv2.weight, shape: [256, 256, 3, 3], requires_grad: True
found backbone_params: encoder.backbone.resnet.layer3.0.bn2.weight, shape: [256], requires_grad: False
found backbone_params: encoder.backbone.resnet.layer3.0.bn2.bias, shape: [256], requires_grad: False
found backbone_params: encoder.backbone.resnet.layer3.0.downsample.0.weight, shape: [256, 128, 1, 1], requires_grad: True
found backbone_params: encoder.backbone.resnet.layer3.0.downsample.1.weight, shape: [256], requires_grad: False
found backbone_params: encoder.backbone.resnet.layer3.0.downsample.1.bias, shape: [256], requires_grad: False
found backbone_params: encoder.backbone.resnet.layer3.1.conv1.weight, shape: [256, 256, 3, 3], requires_grad: True
found backbone_params: encoder.backbone.resnet.layer3.1.bn1.weight, shape: [256], requires_grad: False
found backbone_params: encoder.backbone.resnet.layer3.1.bn1.bias, shape: [256], requires_grad: False
found backbone_params: encoder.backbone.resnet.layer3.1.conv2.weight, shape: [256, 256, 3, 3], requires_grad: True
found backbone_params: encoder.backbone.resnet.layer3.1.bn2.weight, shape: [256], requires_grad: False
found backbone_params: encoder.backbone.resnet.layer3.1.bn2.bias, shape: [256], requires_grad: False
found backbone_params: encoder.backbone.resnet.layer4.0.conv1.weight, shape: [512, 256, 3, 3], requires_grad: True
found backbone_params: encoder.backbone.resnet.layer4.0.bn1.weight, shape: [512], requires_grad: False
found backbone_params: encoder.backbone.resnet.layer4.0.bn1.bias, shape: [512], requires_grad: False
found backbone_params: encoder.backbone.resnet.layer4.0.conv2.weight, shape: [512, 512, 3, 3], requires_grad: True
found backbone_params: encoder.backbone.resnet.layer4.0.bn2.weight, shape: [512], requires_grad: False
found backbone_params: encoder.backbone.resnet.layer4.0.bn2.bias, shape: [512], requires_grad: False
found backbone_params: encoder.backbone.resnet.layer4.0.downsample.0.weight, shape: [512, 256, 1, 1], requires_grad: True
found backbone_params: encoder.backbone.resnet.layer4.0.downsample.1.weight, shape: [512], requires_grad: False
found backbone_params: encoder.backbone.resnet.layer4.0.downsample.1.bias, shape: [512], requires_grad: False
found backbone_params: encoder.backbone.resnet.layer4.1.conv1.weight, shape: [512, 512, 3, 3], requires_grad: True
found backbone_params: encoder.backbone.resnet.layer4.1.bn1.weight, shape: [512], requires_grad: False
found backbone_params: encoder.backbone.resnet.layer4.1.bn1.bias, shape: [512], requires_grad: False
found backbone_params: encoder.backbone.resnet.layer4.1.conv2.weight, shape: [512, 512, 3, 3], requires_grad: True
found backbone_params: encoder.backbone.resnet.layer4.1.bn2.weight, shape: [512], requires_grad: False
found backbone_params: encoder.backbone.resnet.layer4.1.bn2.bias, shape: [512], requires_grad: False
found feat_params: encoder.featnet.upconv5.cbr_unit.0.weight, shape: [256, 512, 3, 3], requires_grad: True
found feat_params: encoder.featnet.upconv5.cbr_unit.0.bias, shape: [256], requires_grad: True
found feat_params: encoder.featnet.iconv4.cbr_unit.0.weight, shape: [256, 512, 3, 3], requires_grad: True
found feat_params: encoder.featnet.iconv4.cbr_unit.0.bias, shape: [256], requires_grad: True
found feat_params: encoder.featnet.upconv4.cbr_unit.0.weight, shape: [128, 256, 3, 3], requires_grad: True
found feat_params: encoder.featnet.upconv4.cbr_unit.0.bias, shape: [128], requires_grad: True
found feat_params: encoder.featnet.iconv3.cbr_unit.0.weight, shape: [128, 256, 3, 3], requires_grad: True
found feat_params: encoder.featnet.iconv3.cbr_unit.0.bias, shape: [128], requires_grad: True
found feat_params: encoder.featnet.upconv3.cbr_unit.0.weight, shape: [64, 128, 3, 3], requires_grad: True
found feat_params: encoder.featnet.upconv3.cbr_unit.0.bias, shape: [64], requires_grad: True
found feat_params: encoder.featnet.iconv2.cbr_unit.0.weight, shape: [64, 128, 3, 3], requires_grad: True
found feat_params: encoder.featnet.iconv2.cbr_unit.0.bias, shape: [64], requires_grad: True
found feat_params: encoder.featnet.proj.weight, shape: [64, 64, 1, 1], requires_grad: True
found feat_params: encoder.featnet.proj.bias, shape: [64], requires_grad: True
found feat_params: encoder.featnet_mesh.stn.conv1.weight, shape: [128, 3, 1], requires_grad: True
found feat_params: encoder.featnet_mesh.stn.conv1.bias, shape: [128], requires_grad: True
found feat_params: encoder.featnet_mesh.stn.fc.weight, shape: [9, 128], requires_grad: True
found feat_params: encoder.featnet_mesh.stn.fc.bias, shape: [9], requires_grad: True
found feat_params: encoder.featnet_mesh.conv1.weight, shape: [64, 3, 1], requires_grad: True
found feat_params: encoder.featnet_mesh.conv1.bias, shape: [64], requires_grad: True
found shape_params: encoder.shape_code_predictor.weight, shape: [64, 512], requires_grad: True
found shape_params: encoder.shape_code_predictor.bias, shape: [64], requires_grad: True
found shape_params: encoder.shape_predictor.shapenerf.layer1.weight, shape: [256, 67], requires_grad: True
found shape_params: encoder.shape_predictor.shapenerf.layer1.bias, shape: [256], requires_grad: True
found shape_params: encoder.shape_predictor.shapenerf.layers_xyz.0.weight, shape: [256, 256], requires_grad: True
found shape_params: encoder.shape_predictor.shapenerf.layers_xyz.0.bias, shape: [256], requires_grad: True
found shape_params: encoder.shape_predictor.shapenerf.layers_dir.0.weight, shape: [128, 256], requires_grad: True
found shape_params: encoder.shape_predictor.shapenerf.layers_dir.0.bias, shape: [128], requires_grad: True
found shape_params: encoder.shape_predictor.shapenerf.fc_alpha.weight, shape: [1, 256], requires_grad: True
found shape_params: encoder.shape_predictor.shapenerf.fc_alpha.bias, shape: [1], requires_grad: True
found shape_params: encoder.shape_predictor.shapenerf.fc_rgb.weight, shape: [3, 128], requires_grad: True
found shape_params: encoder.shape_predictor.shapenerf.fc_rgb.bias, shape: [3], requires_grad: True
found shape_params: encoder.shape_predictor.shapenerf.fc_feat.weight, shape: [256, 256], requires_grad: True
found shape_params: encoder.shape_predictor.shapenerf.fc_feat.bias, shape: [256], requires_grad: True
found cam_params: encoder.pose_predictor.x_offset, shape: [1, 3], requires_grad: False
found cam_params: encoder.pose_predictor.y_offset, shape: [1, 3], requires_grad: False
found cam_params: encoder.pose_predictor.rot_pred_layer.0.0.0.weight, shape: [128, 512], requires_grad: True
found cam_params: encoder.pose_predictor.rot_pred_layer.0.0.0.bias, shape: [128], requires_grad: True
found cam_params: encoder.pose_predictor.rot_pred_layer.0.1.0.weight, shape: [128, 128], requires_grad: True
found cam_params: encoder.pose_predictor.rot_pred_layer.0.1.0.bias, shape: [128], requires_grad: True
found cam_params: encoder.pose_predictor.rot_pred_layer.0.2.0.weight, shape: [128, 128], requires_grad: True
found cam_params: encoder.pose_predictor.rot_pred_layer.0.2.0.bias, shape: [128], requires_grad: True
found cam_params: encoder.pose_predictor.rot_pred_layer.1.weight, shape: [6, 128], requires_grad: True
found cam_params: encoder.pose_predictor.rot_pred_layer.1.bias, shape: [6], requires_grad: True
found cam_params: encoder.pose_predictor.trans_pred_layer.weight, shape: [3, 512], requires_grad: True
found cam_params: encoder.pose_predictor.trans_pred_layer.bias, shape: [3], requires_grad: True
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/pytorch3d/lib/python3.9/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/user/anaconda3/envs/pytorch3d/lib/python3.9/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "train.py", line 43, in main
    trainer.train()
  File "/ssd1/workspace/self-corr-pose/model/trainer.py", line 122, in train
    total_loss.mean().backward()
  File "/home/user/anaconda3/envs/pytorch3d/lib/python3.9/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/home/user/anaconda3/envs/pytorch3d/lib/python3.9/site-packages/torch/autograd/__init__.py", line 197, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [32, 995, 3]], which is output 0 of AsStridedBackward0, is at version 1; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
python-BaseException

**Comment by taeyeopl** [comment]
I found my error comes from here.
https://github.com/kywind/self-corr-pose/blob/b3b46feeeb224eeedd16ca2d76cdf3479505ad5e/model/module/network/shape_predictor.py#L42

It seems work after changing like below. Let me know if you have any ideas. 

`
shape_delta = shape_delta - shape_delta.mean(1, keepdims=True)
`

**Comment by kywind** [comment]
I think it is something related to the python environment that makes that line of code being recognized as an in-place operation. The auto-backpropagation will always produce an error at in-place operations. I see no problems in changing the code like that, it should be fine.

**Comment by taeyeopl** [comment]
Thanks for your reply!
